project:
  type: website
  title: "Bank Account Fraud Detection"

format:
  html:
    theme: flatly
    css: 
      - https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css
      - styles/styles.css
    toc: true
    toc-location: left

engine: "knitr"

editor: visual
