name: CI-CD

on:
  push:
    branches:
      - main
      - error
  pull_request:
    branches:
      - main
      - error

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R_LIBS_USER: ${{ github.workspace }}/R/libs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-R-${{ hashFiles('**/*.qmd') }}
          restore-keys: |
            ${{ runner.os }}-R-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            libicu-dev \
            libpng-dev \
            libjpeg-dev \
            libtiff5-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libfribidi-dev \
            libharfbuzz-dev \
            libglib2.0-dev \
            libmagick++-dev \
            libxslt1-dev

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install R dependencies
        run: |
          mkdir -p $R_LIBS_USER
          Rscript -e "install.packages(c('rmarkdown','tidyverse', 'igraph', 'visNetwork'), repos='https://cloud.r-project.org')"
          Rscript -e "renv::restore()"

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.5.57'

      - name: Render Quarto site
        run: |
          quarto install
          quarto render code/code.qmd

      - name: Set up Git for Deployment
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Update site content" || echo "No changes to commit"

      - name: Deploy Quarto Site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages

      - name: Deploy Data to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
              --destination ${{ secrets.AZURE_CONTAINER_NAME }} \
              --source ./data \
              --overwrite
